# config to get 90.23% sparse ResNet50 on ImageNet. Modify this file to get other sparse models.
# Architecture
arch: ResNet50

# ===== Dataset ===== #
data: /mnt/data/
set: ImageNet
name: STR_90.23

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.256
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.00002251757813 # Change this according to reported numbers in appendix
momentum: 0.875
batch_size: 256
label_smoothing: 0.1

# ===== Sparsity =========== #
conv_type: STRConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
sparse_function: sigmoid
sInit_value: -3200 # Change this according to reported numbers in appendix

# ===== Sparse Initialization =========== #
sparse_init: balanced
init_density: 0.3

# ===== GraNet Parameters ========#
sparse: True
method: None
cosine_prune_rate: 0.1
death_rate: 0.5 # Not needed
prune_rate: 0.5    # Check usage of this parameter. Should be redundant as init_density is used for sparse_init
final_density: 0.05
init_prune_epoch: 35
final_prune_epoch: 50
update_frequency: 3
# l2: 0.0005

# ===== Hardware setup ===== #
workers: 20
