# config to get 90.23% sparse ResNet50 on ImageNet. Modify this file to get other sparse models.
# Architecture
arch: ResNet18

# ===== Dataset ===== #
data: data
set: CIFAR10
name: STR_ResNet18
num_classes: 10

# ===== Learning Rate Policy ======== #
optimizer: sgd
# lr: 0.256
lr: 0.1
lr_policy: cosine_lr
# warmup_length: 5
warmup_length: 0

# ===== Network training config ===== #
epochs: 160
# weight_decay: 0.00002251757813 # Change this according to reported numbers in appendix
weight_decay: 0.0001
# momentum: 0.875
momentum: 0.9
# batch_size: 256
batch_size: 128
label_smoothing: 0.1
final_prune_epoch: 30

# ===== Sparsity =========== #
conv_type: STRConvMask
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
sparse_function: sigmoid
sInit_value: -200 # Change this according to reported numbers in appendix

# ===== GraNet Parameters ========#
sparse: True
method: GraNet
death_rate: 0.5
# optimizer: sgd
sparse_init: ERK
prune_rate: 0.3
init_density: 0.5
final_density: 0.10
update_frequency: 1000
l2: 0.0005

# ===== Hardware setup ===== #
workers: 2
